services:
  # サービス名とコンテナ名は共通のほうが管理しやすい

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    container_name: voicevox
    ports:
    # botとvoicevoxを別コンテナにしているため 
      - "50021:50021"
    tty: true
    restart: always

  rvvot:
    # image: ubuntu:24.04 #build によるdockerfileで指定しているので不要
    build: ./
    container_name: rvvot
    volumes:
      - ./src:/root/src
    env_file:
      - .env
    tty: true
    depends_on:
      - voicevox